### ISSUE TITLE
Documentation improvements - email trail

### ISSUE THREAD

**Issue by adam-rehin** [JiscPER/jper#40]
From: Richard Jones [mailto:richard@cottagelabs.com] 
Sent: 14 October 2015 09:54
To: Adam Rehin Adam.Rehin@jisc.ac.uk
Cc: Steve Byford Steve.Byford@jisc.ac.uk; Mark MacGillivray (mark@cottagelabs.com) mark@cottagelabs.com

Subject: Re: Documentation review please

Yes indeed, that's what the documentation review is intended to do, which is scheduled for when I get back.  Could you reflect this conversation into the issue tracker so that we can pick it up when we're ready?

Cheers,

Richard

On 14 October 2015 at 09:43, Adam Rehin Adam.Rehin@jisc.ac.uk wrote:
Hi Richard 

Thanks the clarification.

Obviously these are the sort of questions that a user of the Router API will have, so your documentation will need to make these things clear.

Regards
Adam

Adam Rehin
Open Access Technical Project Manager

T:    0203 815 5561
M:  07918 564 489
Skype:  adamrehin.jisc
One Castlepark, Tower Hill, Bristol, BS2 0JA
jisc.ac.uk

From: Richard Jones [mailto:richard@cottagelabs.com] 
Sent: 14 October 2015 08:58

To: Adam Rehin Adam.Rehin@jisc.ac.uk
Subject: Re: Documentation review please

On 13 October 2015 at 19:31, Adam Rehin Adam.Rehin@jisc.ac.uk wrote:
Oh, I see. I didn’t realise the {link.url} was already in the Router API form.  Will it include the API_KEY parameter as  part of the construction?

Goodness me, no.  That would be nearly as bad as distributing the user's password!

So, having retrieved the JSON notification using:   GET /api/v1/routed/<repo_id>[?<parameters>], if I wanted to retrieve the fulltext then I would have to check for presence of a link of “type” == ‘fulltext’ and, if found, use the corresponding “url” to retrieve it.  (And if there was more than one link of “type” fulltext, then I could also pick the preferred “format”).

Yes, exactly.

Is it the case that, in general, the content will either be stored within Router (temporary store) and so {link.url} will be of form “/notification/<id>/content?api_key=<api_key>”  or otherwise proxied in which case {link.url} will be of form “/notification/<id>/content/<content_id>?api_key=<api_key>”. 

As a consumer of the notification, there are 3 different kinds of link you might get:

/content -> the original deposit by the publisher
/content/<packaging_format_content_id> -> a router-hosted content package converted from the original deposit to another format you might want
/content/<proxy_content_id> -> a link which will 303 to the public copy when you request it

The latter 2 are indistinguishable from their URL, but the former will contain a "packaging" element and the latter will not.  The main point is that it's irrelevant to the user - they hit the link and they get content.

Will it be possible for both forms of link to exist for a particular notification (i.e. the same content exists in Router temporary store and proxied in Publisher’s store) if so how would I know which links entry is which (without parsing the {link.url})?

Yes to the first.  And no you can't understand them without parsing link.url - that's the point of link.url: it contains the information you need.  We don't anticipate that users will construct their own content urls by guesswork - they should get them from link.url.

Cheers,

Richard

Is that right?

From: Richard Jones [mailto:richard@cottagelabs.com] 
Sent: 13 October 2015 16:06
To: Adam Rehin Adam.Rehin@jisc.ac.uk

Subject: Re: Documentation review please

On 13 October 2015 at 16:00, Adam Rehin Adam.Rehin@jisc.ac.uk wrote:
No I used Windows “snipping tool”… v. easy – perhaps you should give Microsoft a try ;-)

I've checked the weather report for hell, and they say that there's no sign of frost, so could be a while ;)

I’m still missing what happens if they don’t use GET /notification/<id>/content, but instead just do a GET {link.url} – is that an option?

They are the same.  link.url will be a list of URLs for content, one of which will be /notification/<id>/content, others of which will be /notification/<id>/content/<content_id>.

Basically, the link.url field is compliant with the API.  Linked data, sorta.

Cheers,

Richard

Adam
From: Richard Jones [mailto:richard@cottagelabs.com] 
Sent: 13 October 2015 15:11
To: Adam Rehin Adam.Rehin@jisc.ac.uk
Cc: Mark MacGillivray mark@cottagelabs.com
Subject: Re: Documentation review please

Hi Adam,

Did you do that in paint?  very impressive!

There can't be more than one link to the publisher's original deposit package, so there will never be more than one link of that form.  If there are other links, they are of the form /content/<content_id>.  /content is, if I can use a term from physics, the degenerate case - it's the original content, as provided by the publisher.

Cheers,

Richard

On 13 October 2015 at 14:52, Adam Rehin Adam.Rehin@jisc.ac.uk wrote:
Hi Richard

It is still not clear to me whether to retrieve the full text related to a notification is will be possible to do the following:

GET /api/v1/routed/<repo_id>[?<parameters>]

And then, simply issuing a GET using URL found within link.url in the returned JSON package in order to obtain the package.  (In other words, does the GET /notification/<id>/content   call have to be used?). 

Also, I note that in line 403 of the amended documentation the intended text <id> and <content_id> is not being rendered, I assume there is some construct missing.

I am still unclear as to use of GET /notification/<id>/content  (see images):
1.       More than one link can be specified in Outgoing Data Model
2.       If more than 1 link exists (i.e. more than one type of content was supplied by publisher) then what gets returned?
Adam

Adam

From: Richard Jones [mailto:richard@cottagelabs.com] 
Sent: 13 October 2015 14:05
To: Adam Rehin Adam.Rehin@jisc.ac.uk
Cc: Mark MacGillivray mark@cottagelabs.com; Steve Byford Steve.Byford@jisc.ac.uk

Subject: Re: Documentation review please

Hi Adam,

I have made some changes to the source API documentation which hopefully clarifies the things that you are after:

https://github.com/JiscPER/jper/blob/develop/docs/API.md

I notice that you've added further supporting text to your version of the documentation which is not in the source documentation, which is going to give you maintenance and versioning issues in the long run.  

If you want to add to the docs, I'd strongly recommend editing them directly in github (it provides an editing interface, top right of the window the file contents are provided in, icon that looks like a pencil), then they can be version tracked and kept canonical.  

Cheers,

Richard

On 13 October 2015 at 12:05, Adam Rehin Adam.Rehin@jisc.ac.uk wrote:
I may use the Issue tracker in the future, but for now I have used other methods, including (work in progress) comments on the API in a spreadsheet which you haven’t yet seen.

From: Mark MacGillivray [mailto:mark@cottagelabs.com] 
Sent: 13 October 2015 12:00

To: Adam Rehin Adam.Rehin@jisc.ac.uk
Cc: Richard Jones (richard@cottagelabs.com) richard@cottagelabs.com; Steve Byford Steve.Byford@jisc.ac.uk
Subject: Re: Documentation review please

Hello Adam, of course, and to ensure they are as accurate as possible and to ensure that such queries can be answered as accurately and promptly as possible, I would recommend putting them as issues on the code repository on github, in relation to the source documentation files that exist in the code repository. Passing back and forth different versions of PDF documents with commentary on them is less trackable, less efficient, less accurate, and less appropriate to a rapid agile development project such as this.

Here is the link to the issue tracker for the code base:

https://github.com/jiscper/jper/issues

Mark

On Tue, Oct 13, 2015 at 11:56 AM, Adam Rehin Adam.Rehin@jisc.ac.uk wrote:
Hi Mark
We are having to respond to requests from potential users of the API who need to establish integration approaches & plan accordingly, fitting into a product development time-table.  In order to improve likelihood of them integrating with Router in near future they need to see the documentation.  Hence I would like the few queries answered ASAP.
Adam
From: Mark MacGillivray [mailto:mark@cottagelabs.com] 
Sent: 13 October 2015 11:48
To: Adam Rehin Adam.Rehin@jisc.ac.uk
Cc: Richard Jones (richard@cottagelabs.com) richard@cottagelabs.com; Steve Byford Steve.Byford@jisc.ac.uk
Subject: Re: Documentation review please

Hi Adam, we can discuss these points at the Friday meeting. At the moment I would not recommend spending too long on a PDF of the documentation when the underlying source that remains with the code continues to undergo change. Perhaps comments on the API docs there via github issues would be more useful at this stage. Once we get to the technical documentation review, now scheduled for when Richard returns from holiday, we could then check through outstanding issues to ensure the original source documentation in the code repo reflects the functionality at that time.

Mark

On Mon, Oct 12, 2015 at 8:55 AM, Adam Rehin Adam.Rehin@jisc.ac.uk wrote:
Hi Richard, Mark

I’ve compiled a document (based on the GitHub doc) describing the API from a Repository consumer’s perspective.  In doing so I’ve come across a couple of aspects that aren’t clear to me.  These are highlighted (yellow or orange box) in the attached document – would be grateful if you could give response to these ASAP.

Many thanks

Regards
Adam

Adam Rehin
Open Access Technical Project Manager

T:    0203 815 5561
M:  07918 564 489
Skype:  adamrehin.jisc
One Castlepark, Tower Hill, Bristol, BS2 0JA
jisc.ac.uk

Jisc is a registered charity (number 1149740) and a company limited by guarantee which is registered in England under Company No. 5747339, VAT No. GB 197 0632 86. Jisc’s registered office is: One Castlepark, Tower Hill, Bristol, BS2 0JA. T 0203 697 5800.

Jisc Services Limited is a wholly owned Jisc subsidiary and a company limited by guarantee which is registered in England under company number 2881024, VAT number GB 197 0632 86. The registered office is: One Castle Park, Tower Hill, Bristol BS2 0JA. T 0203 697 5800. 
## 

Richard Jones, 

Founder, Cottage Labs 
t: @richard_d_jones, @cottagelabs
w: http://cottagelabs.com
## 

Richard Jones, 

Founder, Cottage Labs 
t: @richard_d_jones, @cottagelabs
w: http://cottagelabs.com
## 

Richard Jones, 

Founder, Cottage Labs 
t: @richard_d_jones, @cottagelabs
w: http://cottagelabs.com
## 

Richard Jones, 

Founder, Cottage Labs 
t: @richard_d_jones, @cottagelabs
w: http://cottagelabs.com
## 

Richard Jones, 

Founder, Cottage Labs 
t: @richard_d_jones, @cottagelabs
w: http://cottagelabs.com
## 

Richard Jones, 

Founder, Cottage Labs 
t: @richard_d_jones, @cottagelabs
w: http://cottagelabs.com

**Comment by richard-jones** [comment]
Actioned the changes that arose from this discussion; I think all other review points are in #42 so closing this one off.
