### ISSUE TITLE
Deployment Architecture documentation

### ISSUE THREAD

**Issue by richard-jones** [JiscPER/jper#43]
Describes the server architecture, storage architecture and network connectivity of the production (live) environment.

Diagram showing servers & their interconnection.

1 section per server that records:
Server purpose
Software stack (including versions)
Application directory structure(s)
Application accounts
Network connections
Server sizing/performance considerations.

Primary audience: Technical manager, system administrators.

**Comment by markmacgillivray** [comment]
In the installation-administration doc
