### ISSUE TITLE
Software build lifecycle documentation

### ISSUE THREAD

**Issue by richard-jones** [JiscPER/jper#45]
A document that describes the software build, test & release tooling and procedures which is used to manage software from source through to production implementation.  Including use of any test harnesses.

**Comment by markmacgillivray** [comment]
Is this necessary? Just checking. How software is built is a matter of preference, and has no practical use after deployment / delivery. Whoever it doing further development later will do it in their own preferred way. Use of test harnesses though - does the test harness have separate documentation already, or does that need written?

**Comment by richard-jones** [comment]
It was in the list of required documentation, but I'm not sure if there was a resolution on that discussion.

**Comment by richard-jones** [comment]
Oh, and the test harness has its own docs, yeah
