### ISSUE TITLE
Administration guide

### ISSUE THREAD

**Issue by richard-jones** [JiscPER/jper#51]
Document areas of the system that require administration, including:
Administration tools / mechanisms
Admin functions that need to be carried out
Step-by-step guides where the process or mechanism isn’t self-explanatory (using the tool interface)
Location of key input/output files, such as configuration, logs
Considerations for production operation, such as the need to monitor the size of particular directories or files

Primary audience: Software support manager, Software support team members.

Should be done in-app, with appropriate context-specific help and help pages where absolutely necessary.

**Comment by markmacgillivray** [comment]
In installation-administration doc
