### ISSUE TITLE
Date format problem on IncomingNotification

### ISSUE THREAD

**Issue by ruben-alonso** [JiscPER/jper#59]
I created a test where, from a JSON document, I create a IncomingNotification JSON structure to send it to the ROUTER. 
To do so, first I create an empty IncomingNotification instance which I later fill in with my JSON information by using the setters provided. Once I have all the fields assigned, I create the url and I do a POST with the IncomingNotification information. 
From this point I have two different scenarios:
-   Windows: I get a 202 response but when the router, which is running on Windows, tries to validate the notification it fails because of (I think) the path that router is trying to access for the notification has a backslash (http://localhost:5999\1de5fac26e8943518f4e94a5c0ba130f). So I tried on Unix.
-   Unix: (ROUTER running on Unix) Using the same test I used in windows I get a 400 response with the following message:
  {"status": "error", "error": "Problem reading notification metadata: Cast with <function datify at 0x7f22b1808500> failed on 2015-07-10"}
  I tried all the formats you specify in the config files but I always get the same response.
  Because of this problem I removed the dates I had set from the IncomingNotification instance and send that to the router. This time I get a 202 response but looking at the router I see the same error but with (I think) the notification date that has been created within the router:
  ERROR in scheduler [/var/www/html/harvester/src/jper/service/scheduler.py:180]:
  Scheduler - Failed scheduled check for unrouted notifications: 'Cast with <function datify at 0x7f22b1808500> failed on 2015-11-20T11:02:51Z'

**Comment by richard-jones** [comment]
Hi @ruben-alonso 

I'm afraid I won't be able to help you on Windows, but hopefully on the linux version ...

Could you attach the url that you are posting to, and the json of the document you are sending to the API.

**Comment by richard-jones** [comment]
Also, could you tell me whether the unit and functional tests succeed when you run them?

Unit tests are in:

```
service/tests/unit
```

Functional tests are in:

```
service/tests/functional
```

If you are in an activated virtualenv, and you have nosetests installed, you can go into each of those directories and run

```
nosetests
```

You should find that 2 of the functional tests fail because they're awaiting a review for the feature they test, but otherwise everything else should work.

If any of them fail, could you let me know which ones and send me the error output.

**Comment by ruben-alonso** [comment]
Hi Richard, 

I just run the functional tests and I am getting 3 errors and 11 failures. I didn't have time to check what the problem is but I am getting the same error I told you last week. For this error to happen it doesn't matter which document I use because it is failing with a date created inside of the Router. I don't know if I failed to install something but I just followed your instructions and they are very simple. Anyway, I will keep investigating to see if I found out why so much tests are failing.
I attached the file with the output from running the functional tests in my machines.

[testlog.txt](https://github.com/JiscPER/jper/files/41795/testlog.txt)

**Comment by richard-jones** [comment]
Hm, ok, weird - I've run the tests myself locally today and all but the 2 expected to fail are passing, so there's something different in our setups, I guess.

I see you're getting some config errors too, which isn't a good sign for your install.

I have also made some major changes today to the submodule dependencies, so perhaps you could try flattening your install, re-cloning the repos, and starting again and let me know how you get on.

**Comment by ruben-alonso** [comment]
Ok, so I deleted everything from my previous instance and installed the new version from git. I run the functional tests and now I am getting new errors. Well, I am just getting one that is making around 8 tests to fail. I attached the output of the run. So the error I am getting in the functional tests is:

ERROR in scheduler [/home/ralonso/router/jper/service/scheduler.py:180]:
Scheduler - Failed scheduled check for unrouted notifications: 'Field 'ref' is not permitted at 'provider.''

and I get the same when I send new notifications to the Router. This happens even though I am not sending any provider information.

[functional_tests.txt](https://github.com/JiscPER/jper/files/43689/functional_tests.txt)

**Comment by richard-jones** [comment]
ok, that sounds kind of promising.  I know what that problem is - it's my fault for messing with the model when I was doing the documentation.  Fix pending, hopefully today.

**Comment by adam-rehin** [comment]
Might there be other issues? Have you got any automatic tests you can run?

**Comment by richard-jones** [comment]
Ok, that's sorted, you should now be able to run the full unit and functional test suite successfully.
