### ISSUE TITLE
Packaging Documentation (https://github.com/JiscPER/jper/blob/develop/docs/api/PACKAGING.md)

### ISSUE THREAD

**Issue by adam-rehin** [JiscPER/jper#80]
The page at: https://github.com/JiscPER/jper/blob/develop/docs/api/PACKAGING.md contains broken links.

The same 2 broken links are repeated 3 times each (in 2 tables and as headings):
http://swordapp.org/docs/sword-profile-1.3.htmlpackage/SimpleZip
https://pubsrouter.jisc.ac.uk/FilesAndJATS

**Comment by richard-jones** [comment]
Yeah, always a bit of confusion there.  These are package identifiers, expressed in the form of URLs, for the purposes of namespacing.  They don't actually resolve to anything, and never will.  But they will always be unique and unambiguous as long as the domains are owned.  A hangover from the semantic web efforts of last decade.

**Comment by richard-jones** [comment]
GitHub markdown appears to convert these to links, even though I haven't specified them as links in the source.

**Comment by adam-rehin** [comment]
Thanks for info. On closer reading I see you have mentioned this in the text.

Is it OK for me to modify these doc pages directly?

**Comment by richard-jones** [comment]
yup, absolutely fine.
